captcha:
  image:
    width: 160
    height: 60
    length: 4
    fonts: []
    characters: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    output_dir: "data/image"

    size: 1000
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    parallel: false
    max_workers: null
    seed: null
    dataset_output_dir: "data/image_dataset"
    